const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");
const hre = require("hardhat");
const {
  time,
  loadFixture,
  reset,
} = require("@nomicfoundation/hardhat-network-helpers");
const {
  concat,
  encodePacked,
  keccak256,
  stringToHex,
  toHex,
} = require("viem");
const { privateKeyToAccount } = require("viem/accounts");

/**
 * SealedBid: acceptance and the append-only bid-set accumulator.
 *
 * Development plan Sections 12.5 and 13, whitepaper Sections 5 and 7.
 *
 * The proofs, the ciphertexts and the committee key all come from the shared
 * fixture, generated by `npm run fixtures:eligibility`. The fixture asserts
 * that each sealed ciphertext's `bidCommitment` equals the proof's public
 * signal 11, so the ciphertext a bidder submits really is the one their proof
 * commits to - a bid that could not be opened to the value the award was
 * computed from would break the whole chain.
 *
 * Receipts are signed HERE, by test wallets registered as replicas, using an
 * independent implementation of the Section 22 digest. The replica service
 * has a third implementation. Three independent computations of one digest is
 * how the encoding stays honest.
 */

const FIX = JSON.parse(
  readFileSync(
    join(__dirname, "../../circuits/fixtures/eligibility.proof.json"),
    "utf8",
  ),
);
const CHAIN = FIX.chain;
const SPEC = FIX.tender;
const SEALED = FIX.sealed;

const {
  publicKey: COMMITTEE_Y,
  committeeArgs: dealtCommitteeArgs,
} = require("./helpers/committee.cjs");

/** keccak256("FairProof:receipt:v1"), spec Section 13. */
const RAW_RECEIPT_V1 =
  "0x6f914b0c1addf20f03c49bb18eb568ad66529197270c1c525f3867fdef721325";
/** keccak256("FairProof:receiptSig:v1"), spec Section 22. */
const RAW_RECEIPT_SIG_V1 =
  "0xc3ffb182dd3ebfe5535def6710ba4562e2bf2416e6ac55e4ac25fc7e14433ea3";

const Action = { ActivateVerifierVersion: 3 };
const TIMELOCK = 60;
const REVIEW_WINDOW = BigInt(SPEC.reviewWindow);
const VKEY_HASH = keccak256(stringToHex("vkey"));
const SOURCE_HASH = keccak256(stringToHex("source"));

/** Three replica signing keys. Public test keys; never reused anywhere real. */
const REPLICA_KEYS = [
  "0x" + "a1".repeat(32),
  "0x" + "b2".repeat(32),
  "0x" + "c3".repeat(32),
];

const proofArgs = (name) => {
  const f = FIX.fixtures[name];
  return [f.pA.map(BigInt), f.pB.map((r) => r.map(BigInt)), f.pC.map(BigInt)];
};
const signalsOf = (name) => FIX.fixtures[name].publicSignals.map(BigInt);

/**
 * The Section 22 digest, computed independently of the contract and of the
 * crypto package.
 */
function receiptSigDigest(replicaId, contentHash, byteLength) {
  return keccak256(
    encodePacked(
      ["bytes32", "uint8", "bytes32", "uint64"],
      [RAW_RECEIPT_SIG_V1, replicaId, contentHash, BigInt(byteLength)],
    ),
  );
}

describe("SealedBid", function () {
  this.timeout(300000);

  let gov, reg, tr, groth, ev, sb;
  let council, authority, outsider, committee;
  let tenderId;
  let replicas;
  let poseidonLibs;

  const committeeArgs = () =>
    dealtCommitteeArgs(committee.map((w) => w.account.address));

  /** A signed receipt from one replica for the given content. */
  async function receipt(replicaId, contentHash, byteLength) {
    const account = privateKeyToAccount(REPLICA_KEYS[replicaId - 1]);
    const digest = receiptSigDigest(replicaId, contentHash, byteLength);
    const signature = await account.sign({ hash: digest });
    return { replicaId, contentHash, byteLength: BigInt(byteLength), signature };
  }

  /** Receipts from the given replicas, in ascending order. */
  async function receiptsFor(name, replicaIds = [1, 2, 3]) {
    const s = SEALED[name];
    return Promise.all(
      [...replicaIds].sort((a, b) => a - b).map((id) =>
        receipt(id, s.ciphertextHash, s.byteLength),
      ),
    );
  }

  const submission = (name) => ({
    tenderId,
    nullifier: signalsOf(name)[10],
    bidCommitment: signalsOf(name)[11],
    ciphertextHash: SEALED[name].ciphertextHash,
  });

  async function submit(name, overrides = {}) {
    const [a, b, c] = proofArgs(name);
    const rs = overrides.receipts ?? (await receiptsFor(name));
    return sb.write.submitBid(
      [{ ...submission(name), ...(overrides.submission ?? {}) }, rs, a, b, c],
      { account: (overrides.account ?? outsider).account },
    );
  }

  function ruleFields(overrides = {}) {
    return {
      requirements: {
        turnoverThreshold: BigInt(SPEC.turnoverThreshold),
        experienceMonths: Number(SPEC.experienceMonthsThreshold),
        certificationCode: BigInt(SPEC.requiredCertificationCode),
      },
      biddingStart: BigInt(SPEC.biddingStart),
      deadline: BigInt(SPEC.deadline),
      requiredIssuerId: keccak256(stringToHex(SPEC.requiredIssuerId)),
      issuerEpoch: BigInt(SPEC.credentialEpoch),
      schemaVersion: SPEC.schemaVersion,
      verifierVersion: SPEC.verifierVersion,
      disclosurePolicy: SPEC.disclosurePolicy,
      awardRule: SPEC.awardRule,
      tieBreakRule: SPEC.tieBreakRule,
      contingencyPolicy: SPEC.contingencyPolicy,
      reviewWindow: REVIEW_WINDOW,
      ...overrides,
    };
  }

  /**
   * Start from a clean network.
   *
   * These tests move the clock to a deadline in 2096. Mocha runs every test
   * file in one process against one network, so without this the NEXT file's
   * first fixture inherits a clock past that deadline and fails while setting
   * up a bidding window - a failure that points at the wrong file entirely.
   * `reset` also clears the fixture snapshot cache, which a bare
   * hardhat_reset would leave dangling.
   */
  before(async () => {
    await reset();
  });

  after(async () => {
    await reset();
  });

  /**
   * Deploy everything, register the replicas and the verifier, and activate
   * the fixture's tender with a bidding window that is open now.
   *
   * Run through `loadFixture` rather than a plain `beforeEach` because these
   * tests move the clock. One test advances past the fixture's deadline, and
   * without a snapshot the next test's setup computed a `biddingStart` beyond
   * that deadline and failed with `InvalidBiddingWindow` - a confusing
   * failure in a test that had nothing to do with windows. `loadFixture`
   * restores the chain, clock included, between tests.
   */
  async function deployAll() {
    const w = await hre.viem.getWalletClients();
    const councilW = w.slice(0, 4);
    const authorityW = w[4];
    const outsiderW = w[5];
    const committeeW = w.slice(6, 11);

    const govC = await hre.viem.deployContract("Governance", [
      councilW.map((x) => x.account.address),
    ]);
    const regC = await hre.viem.deployContract("IssuerRegistry", [govC.address]);
    const trC = await hre.viem.deployContract("TenderRegistry", [
      govC.address, regC.address, REVIEW_WINDOW,
    ]);
    const grothC = await hre.viem.deployContract("EligibilityVerifierGroth16", []);
    const evC = await hre.viem.deployContract("EligibilityVerifier", [
      govC.address, regC.address, trC.address,
    ]);

    // SealedBid computes Poseidon on-chain - that is the point of it - so the
    // generated libraries must be deployed and linked. TenderRegistry needs
    // no link because it only uses the keccak-based helpers.
    const t3 = await hre.viem.deployContract("PoseidonT3");
    const t6 = await hre.viem.deployContract("PoseidonT6");
    const libs = {
      "poseidon-solidity/PoseidonT3.sol:PoseidonT3": t3.address,
      "poseidon-solidity/PoseidonT6.sol:PoseidonT6": t6.address,
    };
    const sbC = await hre.viem.deployContract(
      "SealedBid",
      [govC.address, trC.address, evC.address],
      { libraries: libs },
    );

    await regC.write.setTenderModule([trC.address], { account: councilW[0].account });
    const epoch = BigInt(SPEC.credentialEpoch);
    await regC.write.publishIssuerRegistryRoot([epoch, CHAIN.issuerRegistryRoot], {
      account: councilW[0].account,
    });
    await regC.write.publishRevocationRoot([epoch, CHAIN.revocationRoot], {
      account: councilW[0].account,
    });
    await trC.write.setTenderAuthority([authorityW.account.address, true], {
      account: councilW[0].account,
    });

    const replicaList = REPLICA_KEYS.map((k, i) => ({
      replicaId: i + 1,
      address: privateKeyToAccount(k).address,
    }));
    for (const r of replicaList) {
      await sbC.write.registerReplica([r.replicaId, r.address, `replica-${r.replicaId}`], {
        account: councilW[0].account,
      });
    }

    // ---- verifier version 1, through the real governance flow -------------
    const r = {
      version: 1,
      impl: grothC.address,
      vkeyHash: VKEY_HASH,
      sourceHash: SOURCE_HASH,
      transcriptUri: "ceremony",
    };
    const payload = await evC.read.encodeActivationPayload([r]);
    await govC.write.propose([Action.ActivateVerifierVersion, payload, "v1"], {
      account: councilW[0].account,
    });
    const proposalId = await govC.read.proposalCount();
    await govC.write.approve([proposalId], { account: councilW[1].account });
    await govC.write.approve([proposalId], { account: councilW[2].account });
    await time.increase(TIMELOCK + 1);
    await govC.write.execute([proposalId], { account: councilW[0].account });
    const [pa, pb, pc] = proofArgs("valid");
    await evC.write.registerVerifier(
      [proposalId, r, { a: pa, b: pb, c: pc, signals: signalsOf("valid") }],
      { account: councilW[0].account },
    );

    // ---- the fixture's tender, with a window that is open NOW -------------
    //
    // The fixture's own window is in 2096 so unit tests can activate it
    // without the timestamps rotting. Bidding has to be open here, so the
    // window is moved to the present. That does not disturb the proofs:
    // `deadline` is public signal 6 and stays exactly as proved, while
    // `biddingStart` is not a signal at all and only governs the window.
    const now = BigInt(await time.latest());
    const biddingStart = now + REVIEW_WINDOW + 10n;
    const id = keccak256(stringToHex(CHAIN.tenderIdString));

    await trC.write.createTender([CHAIN.tenderIdString], { account: authorityW.account });
    await trC.write.setRuleDocument([id, stringToHex(CHAIN.canonicalRuleDocument)], {
      account: authorityW.account,
    });
    await trC.write.setRuleFields([id, ruleFields({ biddingStart })], {
      account: authorityW.account,
    });
    await trC.write.setCommitteeKey(
      [id, COMMITTEE_Y.x, COMMITTEE_Y.y, ...dealtCommitteeArgs(committeeW.map((x) => x.account.address))],
      { account: authorityW.account },
    );
    await trC.write.activateTender([id, CHAIN.rulesHash], { account: authorityW.account });
    await time.increaseTo(biddingStart + 1n);

    return {
      gov: govC, reg: regC, tr: trC, groth: grothC, ev: evC, sb: sbC,
      council: councilW, authority: authorityW, outsider: outsiderW,
      committee: committeeW, tenderId: id, replicas: replicaList,
      poseidonLibs: libs,
    };
  }

  beforeEach(async () => {
    ({
      gov, reg, tr, groth, ev, sb,
      council, authority, outsider, committee,
      tenderId, replicas, poseidonLibs,
    } = await loadFixture(deployAll));
  });

  // ------------------------------------------------------------------ setup

  describe("the fixture ties the proof to the ciphertext", () => {
    it("each sealed ciphertext's bidCommitment is the proof's public signal 11", () => {
      // Asserted in the generator too; repeated here because it is the hinge
      // of the whole design. If these diverged, an accepted bid could not be
      // opened to the value the award was computed from.
      for (const name of ["valid", "secondBidder"]) {
        assert.equal(BigInt(SEALED[name].bidCommitment), signalsOf(name)[11]);
      }
    });

    it("the two bidders have distinct nullifiers and ciphertexts", () => {
      assert.notEqual(signalsOf("valid")[10], signalsOf("secondBidder")[10]);
      assert.notEqual(SEALED.valid.ciphertextHash, SEALED.secondBidder.ciphertextHash);
    });

    it("bidding is open and capacity is MAX_BIDS", async () => {
      assert.equal(await tr.read.isBiddingOpen([tenderId]), true);
      assert.equal(await sb.read.MAX_BIDS(), 32);
      assert.equal(await sb.read.remainingCapacity([tenderId]), 32);
      assert.equal(await sb.read.bidSetRoot([tenderId]), 0n);
    });
  });

  // ------------------------------------------------------------- acceptance

  describe("accepting a bid", () => {
    it("accepts a valid bid and appends its leaf", async () => {
      await submit("valid");
      assert.equal(await sb.read.submissionCount([tenderId]), 1n);

      const bid = await sb.read.getBid([tenderId, 0n]);
      assert.equal(bid.nullifier, signalsOf("valid")[10]);
      assert.equal(bid.bidCommitment, signalsOf("valid")[11]);
      assert.equal(bid.ciphertextHash, SEALED.valid.ciphertextHash);
      assert.equal(bid.submissionIndex, 0);
      assert.notEqual(bid.storageReceiptRoot, 0n);

      const root = await sb.read.bidSetRoot([tenderId]);
      assert.notEqual(root, 0n);
      assert.equal(await sb.read.remainingCapacity([tenderId]), 31);
    });

    it("the leaf is the contract's own Poseidon of four inputs plus the domain", async () => {
      // The completeness claim rests on the CONTRACT computing this, not the
      // authority. Recomputed here through the encoding harness, which is a
      // different code path from SealedBid's.
      await submit("valid");
      const bid = await sb.read.getBid([tenderId, 0n]);
      const harness = await hre.viem.deployContract("EncodingHarness", [], {
        libraries: poseidonLibs,
      });
      const expected = await harness.read.bidLeaf([
        signalsOf("valid")[10],
        signalsOf("valid")[11],
        await harness.read.toField([SEALED.valid.ciphertextHash]),
        0n,
      ]);
      assert.equal(bid.leaf, expected);
    });

    it("accepts two distinct bidders and the root changes", async () => {
      await submit("valid");
      const afterOne = await sb.read.bidSetRoot([tenderId]);
      await submit("secondBidder");
      const afterTwo = await sb.read.bidSetRoot([tenderId]);
      assert.equal(await sb.read.submissionCount([tenderId]), 2n);
      assert.notEqual(afterOne, afterTwo);

      const leaves = await sb.read.getLeaves([tenderId]);
      assert.equal(leaves.length, 2);
      assert.equal((await sb.read.getBid([tenderId, 1n])).submissionIndex, 1);
    });

    it("submission is permissionless - anyone may pay", async () => {
      // What authorises a bid is the proof, not the sender. And because gas is
      // free on this network the sender can be a fresh zero-balance address,
      // which removes the wallet-funding correlation channel whitepaper
      // Table 4 lists as a residual metadata risk.
      const fresh = (await hre.viem.getWalletClients())[15];
      await submit("valid", { account: fresh });
      const bid = await sb.read.getBid([tenderId, 0n]);
      assert.equal(bid.submitter.toLowerCase(), fresh.account.address.toLowerCase());
    });

    it("emits everything needed to reproduce the root from events alone", async () => {
      const hash = await submit("valid");
      const client = await hre.viem.getPublicClient();
      await client.waitForTransactionReceipt({ hash });
      const logs = await client.getContractEvents({
        address: sb.address,
        abi: sb.abi,
        eventName: "BidAccepted",
      });
      assert.equal(logs.length, 1);
      const a = logs[0].args;
      assert.equal(a.nullifier, signalsOf("valid")[10]);
      assert.equal(a.bidCommitment, signalsOf("valid")[11]);
      assert.equal(a.ciphertextHash, SEALED.valid.ciphertextHash);
      assert.equal(a.submissionIndex, 0);
      assert.equal(a.bidSetRoot, await sb.read.bidSetRoot([tenderId]));
      assert.equal(a.leaf, (await sb.read.getBid([tenderId, 0n])).leaf);
    });
  });

  // ---------------------------------------------------------- the nullifier

  describe("one bid per credential per tender", () => {
    it("rejects a second bid with the same nullifier", async () => {
      await submit("valid");
      assert.equal(await sb.read.nullifierUsed([tenderId, signalsOf("valid")[10]]), true);
      await assert.rejects(() => submit("valid"), /NullifierAlreadyUsed/);
    });

    it("rejects a replay of the same ciphertext under a new commitment", async () => {
      // Two bids that open to the same payload; one is a replay. Forbidding
      // it also closes a griefing path where a watcher resubmits someone
      // else's ciphertext.
      await submit("valid");
      await assert.rejects(
        async () =>
          submit("secondBidder", {
            submission: { ciphertextHash: SEALED.valid.ciphertextHash },
            receipts: await receiptsFor("valid"),
          }),
        /CiphertextAlreadySubmitted/,
      );
    });

    it("rejects a zero nullifier or commitment", async () => {
      await assert.rejects(
        async () => submit("valid", { submission: { nullifier: 0n } }),
        /ZeroCommitment/,
      );
      await assert.rejects(
        async () => submit("valid", { submission: { bidCommitment: 0n } }),
        /ZeroCommitment/,
      );
    });
  });

  // ------------------------------------------------------- the storage quorum

  describe("the 2-of-3 storage quorum", () => {
    it("accepts two receipts - one replica may be down", async () => {
      await submit("valid", { receipts: await receiptsFor("valid", [1, 3]) });
      assert.equal(await sb.read.submissionCount([tenderId]), 1n);
    });

    it("a two-replica receipt root differs from a three-replica one", async () => {
      await submit("valid", { receipts: await receiptsFor("valid", [1, 3]) });
      const two = (await sb.read.getBid([tenderId, 0n])).storageReceiptRoot;
      await submit("secondBidder", { receipts: await receiptsFor("secondBidder") });
      const three = (await sb.read.getBid([tenderId, 1n])).storageReceiptRoot;
      assert.notEqual(two, three);
    });

    it("REJECTS a single receipt", async () => {
      // The check that makes the quorum real. A commitment must never enter
      // bidSetRoot when only one replica holds the ciphertext, or a single
      // failure makes the bid unopenable and the completeness claim false.
      await assert.rejects(
        async () => submit("valid", { receipts: await receiptsFor("valid", [2]) }),
        /StorageQuorumNotMet/,
      );
    });

    it("REJECTS no receipts at all", async () => {
      await assert.rejects(
        async () => submit("valid", { receipts: [] }),
        /StorageQuorumNotMet/,
      );
    });

    it("rejects two receipts from the SAME replica", async () => {
      // Two acknowledgements from one replica are not two acknowledgements.
      const r = await receipt(1, SEALED.valid.ciphertextHash, SEALED.valid.byteLength);
      await assert.rejects(
        async () => submit("valid", { receipts: [r, { ...r }] }),
        /ReceiptsNotOrdered/,
      );
    });

    it("rejects receipts that are not in ascending replica order", async () => {
      const rs = await receiptsFor("valid", [1, 2]);
      await assert.rejects(
        async () => submit("valid", { receipts: [rs[1], rs[0]] }),
        /ReceiptsNotOrdered/,
      );
    });

    it("rejects a receipt for a DIFFERENT ciphertext", async () => {
      // A replica may well hold the other object; that is not an
      // acknowledgement of this one.
      const wrong = await Promise.all([
        receipt(1, SEALED.secondBidder.ciphertextHash, SEALED.secondBidder.byteLength),
        receipt(2, SEALED.secondBidder.ciphertextHash, SEALED.secondBidder.byteLength),
      ]);
      await assert.rejects(
        async () => submit("valid", { receipts: wrong }),
        /ReceiptContentMismatch/,
      );
    });

    it("rejects a receipt signed by an unregistered key", async () => {
      const rogue = privateKeyToAccount("0x" + "de".repeat(32));
      const digest = receiptSigDigest(2, SEALED.valid.ciphertextHash, SEALED.valid.byteLength);
      const forged = {
        replicaId: 2,
        contentHash: SEALED.valid.ciphertextHash,
        byteLength: BigInt(SEALED.valid.byteLength),
        signature: await rogue.sign({ hash: digest }),
      };
      const good = await receipt(1, SEALED.valid.ciphertextHash, SEALED.valid.byteLength);
      await assert.rejects(
        async () => submit("valid", { receipts: [good, forged] }),
        /ReceiptSignatureInvalid/,
      );
    });

    it("rejects a receipt whose byteLength was altered", async () => {
      // The length is inside the signed digest, so changing it invalidates
      // the signature rather than being silently accepted.
      const rs = await receiptsFor("valid", [1, 2]);
      rs[1] = { ...rs[1], byteLength: rs[1].byteLength + 1n };
      await assert.rejects(
        async () => submit("valid", { receipts: rs }),
        /ReceiptSignatureInvalid/,
      );
    });

    it("rejects a malformed signature length", async () => {
      const rs = await receiptsFor("valid", [1, 2]);
      rs[1] = { ...rs[1], signature: "0x1234" };
      await assert.rejects(
        async () => submit("valid", { receipts: rs }),
        /ReceiptSignatureLength/,
      );
    });

    it("rejects a receipt from an unknown replica id", async () => {
      const good = await receipt(1, SEALED.valid.ciphertextHash, SEALED.valid.byteLength);
      const unknown = {
        replicaId: 3,
        contentHash: SEALED.valid.ciphertextHash,
        byteLength: BigInt(SEALED.valid.byteLength),
        signature: good.signature,
      };
      // Deploy a fresh SealedBid with only replicas 1 and 2 registered.
      const fresh = await hre.viem.deployContract(
        "SealedBid",
        [gov.address, tr.address, ev.address],
        { libraries: poseidonLibs },
      );
      for (const id of [1, 2]) {
        await fresh.write.registerReplica(
          [id, replicas[id - 1].address, `replica-${id}`],
          { account: council[0].account },
        );
      }
      const [a, b, c] = proofArgs("valid");
      await assert.rejects(
        async () =>
          fresh.write.submitBid([submission("valid"), [good, unknown], a, b, c], {
            account: outsider.account,
          }),
        /UnknownReplica/,
      );
    });

    it("a deactivated replica stops counting towards the quorum", async () => {
      await sb.write.setReplicaStatus([2, false, "suspected key compromise"], {
        account: council[0].account,
      });
      await assert.rejects(
        async () => submit("valid", { receipts: await receiptsFor("valid", [1, 2]) }),
        /InactiveReplica/,
      );
      // The other two still work, so deactivating one does not halt the tender.
      await submit("valid", { receipts: await receiptsFor("valid", [1, 3]) });
      assert.equal(await sb.read.submissionCount([tenderId]), 1n);
    });

    it("rejects more receipts than there are replicas", async () => {
      const rs = await receiptsFor("valid");
      await assert.rejects(
        () => submit("valid", { receipts: [...rs, rs[2]] }),
        /TooManyReceipts/,
      );
    });
  });

  // -------------------------------------------------------- the eligibility

  describe("the eligibility proof is required", () => {
    it("REJECTS a bid whose proof is for a different tender", async () => {
      const [a, b, c] = proofArgs("otherTender");
      const s = {
        tenderId,
        nullifier: signalsOf("otherTender")[10],
        bidCommitment: signalsOf("otherTender")[11],
        ciphertextHash: SEALED.valid.ciphertextHash,
      };
      await assert.rejects(
        async () =>
          sb.write.submitBid([s, await receiptsFor("valid"), a, b, c], {
            account: outsider.account,
          }),
        /ProofRejected/,
      );
      assert.equal(await sb.read.submissionCount([tenderId]), 0n);
    });

    it("REJECTS a bid proved against thresholds the bidder chose", async () => {
      const [a, b, c] = proofArgs("weakThresholds");
      const s = {
        tenderId,
        nullifier: signalsOf("weakThresholds")[10],
        bidCommitment: signalsOf("weakThresholds")[11],
        ciphertextHash: SEALED.valid.ciphertextHash,
      };
      await assert.rejects(
        async () =>
          sb.write.submitBid([s, await receiptsFor("valid"), a, b, c], {
            account: outsider.account,
          }),
        /ProofRejected/,
      );
    });

    it("rejects a proof re-used with a different nullifier", async () => {
      await assert.rejects(
        async () =>
          submit("valid", {
            submission: { nullifier: signalsOf("secondBidder")[10] },
          }),
        /ProofRejected/,
      );
    });

    it("rejects a tampered proof", async () => {
      const [a, b, c] = proofArgs("valid");
      await assert.rejects(
        async () =>
          sb.write.submitBid(
            [submission("valid"), await receiptsFor("valid"), [a[0] + 1n, a[1]], b, c],
            { account: outsider.account },
          ),
        /ProofRejected/,
      );
    });

    it("nothing is written when the proof fails", async () => {
      // Every mutation happens after the proof check, so a rejected
      // submission must leave no trace - not a used nullifier, not a leaf.
      const [a, b, c] = proofArgs("weakThresholds");
      const nul = signalsOf("weakThresholds")[10];
      await assert.rejects(
        async () =>
          sb.write.submitBid(
            [
              { tenderId, nullifier: nul, bidCommitment: signalsOf("weakThresholds")[11], ciphertextHash: SEALED.valid.ciphertextHash },
              await receiptsFor("valid"), a, b, c,
            ],
            { account: outsider.account },
          ),
        /ProofRejected/,
      );
      assert.equal(await sb.read.nullifierUsed([tenderId, nul]), false);
      assert.equal(await sb.read.ciphertextUsed([tenderId, SEALED.valid.ciphertextHash]), false);
      assert.equal(await sb.read.submissionCount([tenderId]), 0n);
      assert.equal(await sb.read.bidSetRoot([tenderId]), 0n);
    });
  });

  // ------------------------------------------------------------- the window

  describe("the bidding window", () => {
    it("rejects a bid before the review window elapses", async () => {
      // A fresh tender that is ACTIVE but still in its review window.
      const idString = `${CHAIN.tenderIdString}-early`;
      const id = keccak256(stringToHex(idString));
      const now = BigInt(await time.latest());
      const biddingStart = now + REVIEW_WINDOW + 100n;
      await tr.write.createTender([idString], { account: authority.account });
      await tr.write.setRuleDocument([id, stringToHex(CHAIN.canonicalRuleDocument)], {
        account: authority.account,
      });
      await tr.write.setRuleFields([id, ruleFields({ biddingStart })], {
        account: authority.account,
      });
      await tr.write.setCommitteeKey(
        [id, COMMITTEE_Y.x, COMMITTEE_Y.y, ...committeeArgs()],
        { account: authority.account },
      );
      await tr.write.activateTender([id, CHAIN.rulesHash], { account: authority.account });

      assert.equal(await tr.read.isBiddingOpen([id]), false);
      const [a, b, c] = proofArgs("valid");
      await assert.rejects(
        async () =>
          sb.write.submitBid(
            [{ ...submission("valid"), tenderId: id }, await receiptsFor("valid"), a, b, c],
            { account: outsider.account },
          ),
        /BiddingNotOpen/,
      );
    });

    it("rejects a bid after the deadline", async () => {
      await time.increaseTo(BigInt(SPEC.deadline) + 1n);
      assert.equal(await tr.read.isBiddingOpen([tenderId]), false);
      await assert.rejects(() => submit("valid"), /BiddingNotOpen/);
    });

    it("rejects a bid on a tender that does not exist", async () => {
      const [a, b, c] = proofArgs("valid");
      await assert.rejects(
        async () =>
          sb.write.submitBid(
            [
              { ...submission("valid"), tenderId: keccak256(stringToHex("nope")) },
              await receiptsFor("valid"), a, b, c,
            ],
            { account: outsider.account },
          ),
        /BiddingNotOpen/,
      );
    });

    it("rejects bids while the system is paused", async () => {
      await gov.write.propose([7, "0x", "emergency"], { account: council[0].account });
      const id = await gov.read.proposalCount();
      await gov.write.approve([id], { account: council[1].account });
      await gov.write.approve([id], { account: council[2].account });
      await gov.write.execute([id], { account: council[0].account });
      assert.equal(await gov.read.paused(), true);
      await assert.rejects(() => submit("valid"), /SystemPaused/);
    });
  });

  // ------------------------------------------------------------ the replicas

  describe("replica registration", () => {
    it("is council-only and one-shot per id", async () => {
      // A re-settable replica key would let a captured council key make an
      // old receipt verify, or stop it verifying, and receipts are what the
      // completeness claim rests on.
      await assert.rejects(
        async () =>
          sb.write.registerReplica([1, outsider.account.address, "x"], {
            account: outsider.account,
          }),
        /NotCouncilMember/,
      );
      await assert.rejects(
        async () =>
          sb.write.registerReplica([1, outsider.account.address, "x"], {
            account: council[0].account,
          }),
        /ReplicaAlreadyRegistered/,
      );
    });

    it("rejects replica id zero and ids above the replica count", async () => {
      const fresh = await hre.viem.deployContract(
        "SealedBid",
        [gov.address, tr.address, ev.address],
        { libraries: poseidonLibs },
      );
      for (const id of [0, 4, 255]) {
        await assert.rejects(
          async () =>
            fresh.write.registerReplica([id, outsider.account.address, "x"], {
              account: council[0].account,
            }),
          /InvalidReplicaId/,
        );
      }
    });

    it("rejects two replicas sharing one signing key", async () => {
      // Two replicas with one key are one replica wearing two hats, and would
      // satisfy a 2-of-3 quorum on their own.
      const fresh = await hre.viem.deployContract(
        "SealedBid",
        [gov.address, tr.address, ev.address],
        { libraries: poseidonLibs },
      );
      await fresh.write.registerReplica([1, replicas[0].address, "one"], {
        account: council[0].account,
      });
      await assert.rejects(
        async () =>
          fresh.write.registerReplica([2, replicas[0].address, "two"], {
            account: council[0].account,
          }),
        /DuplicateReplicaSigner/,
      );
    });

    it("status changes require a reason and are attributable", async () => {
      await assert.rejects(
        async () => sb.write.setReplicaStatus([1, false, ""], { account: council[0].account }),
        /ReasonRequired/,
      );
      await sb.write.setReplicaStatus([1, false, "disk failure"], {
        account: council[0].account,
      });
      assert.equal((await sb.read.getReplica([1])).active, false);
      assert.equal(await sb.read.activeReplicaCount(), 2);
      await sb.write.setReplicaStatus([1, true, "restored"], {
        account: council[0].account,
      });
      assert.equal(await sb.read.activeReplicaCount(), 3);
    });
  });

  // -------------------------------------------------------------- gas record

  describe("gas (plan Section 20.6 benchmark record)", () => {
    it("reports the measured cost of accepting a bid", async () => {
      const client = await hre.viem.getPublicClient();
      const [a, b, c] = proofArgs("valid");
      const rs = await receiptsFor("valid");
      const three = await client.estimateContractGas({
        address: sb.address,
        abi: sb.abi,
        functionName: "submitBid",
        args: [submission("valid"), rs, a, b, c],
        account: outsider.account,
      });
      const two = await client.estimateContractGas({
        address: sb.address,
        abi: sb.abi,
        functionName: "submitBid",
        args: [submission("valid"), await receiptsFor("valid", [1, 3]), a, b, c],
        account: outsider.account,
      });
      console.log(`      submitBid, 3 receipts: ${three}`);
      console.log(`      submitBid, 2 receipts: ${two}`);
      // Poseidon on-chain plus a pairing check; a small number would mean
      // something was skipped, not that the code got fast.
      assert.ok(three > 500000n, "acceptance cannot be this cheap");
    });
  });
});
