/**
 * BabyJubjub curve arithmetic.
 *
 * BabyJubjub is the twisted Edwards curve whose base field is BN254's SCALAR
 * field, which is what makes its arithmetic expressible inside a BN254
 * circuit. It is the curve for issuer signatures (EdDSA), the tender
 * committee's ElGamal key, and the Chaum-Pedersen DLEQ proofs that make
 * decryption shares publicly verifiable.
 *
 * Uses circomlibjs, so the point encoding and constants are byte-identical to
 * circomlib's Circom templates and to `packages/contracts/lib/BabyJubjub.sol`
 * (agreement enforced by the cross-language test). Do not reimplement the
 * arithmetic here: a subtly different encoding produces values that fail in
 * the circuit or on-chain for reasons that look like a curve bug.
 *
 * TWO DIFFERENT ORDERS, AND WHY IT MATTERS. The curve group has order
 * `8 * subOrder`. Every value used as a secret scalar must be reduced modulo
 * `SUB_ORDER`, not modulo the field prime and not modulo the full order.
 * Lagrange interpolation for threshold reconstruction likewise happens modulo
 * `SUB_ORDER`, because that is the order of the group the exponents live in.
 * Reducing modulo the wrong modulus produces shares that verify individually
 * and then reconstruct to the wrong secret.
 */
import { buildBabyjub } from "circomlibjs";

/** An affine BabyJubjub point. */
export interface Point {
  x: bigint;
  y: bigint;
}

type BabyJub = {
  F: { e(v: bigint | string | number): Uint8Array; toObject(v: Uint8Array): bigint };
  Base8: [Uint8Array, Uint8Array];
  order: bigint;
  subOrder: bigint;
  A: unknown;
  D: unknown;
  addPoint(a: [Uint8Array, Uint8Array], b: [Uint8Array, Uint8Array]): [Uint8Array, Uint8Array];
  mulPointEscalar(p: [Uint8Array, Uint8Array], e: bigint): [Uint8Array, Uint8Array];
  inCurve(p: [Uint8Array, Uint8Array]): boolean;
};

let babyjub: BabyJub | undefined;

/** Initialise the curve once. Must be awaited before any other call. */
export async function initBabyjub(): Promise<void> {
  if (!babyjub) babyjub = (await buildBabyjub()) as unknown as BabyJub;
}

function jub(): BabyJub {
  if (!babyjub) throw new Error("babyjub: call await initBabyjub() first");
  return babyjub;
}

/** The base field prime; equal to BN254's scalar field prime. */
export const CURVE_PRIME =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

/** Twisted Edwards parameters: a*x^2 + y^2 = 1 + d*x^2*y^2. */
export const CURVE_A = 168700n;
export const CURVE_D = 168696n;

/** Order of the prime-order subgroup generated by BASE8. */
export const SUB_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

/** The generator of the prime-order subgroup (circomlib's Base8). */
export const BASE8: Point = {
  x: 5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  y: 16950150798460657717958625567821834550301663161624707787222815936182638968203n,
};

/** The identity element of the group. */
export const IDENTITY: Point = { x: 0n, y: 1n };

const toF = (p: Point): [Uint8Array, Uint8Array] => {
  const F = jub().F;
  return [F.e(p.x), F.e(p.y)];
};

const fromF = (p: [Uint8Array, Uint8Array]): Point => {
  const F = jub().F;
  return { x: F.toObject(p[0]), y: F.toObject(p[1]) };
};

export function addPoint(a: Point, b: Point): Point {
  return fromF(jub().addPoint(toF(a), toF(b)));
}

/**
 * Scalar multiplication. The scalar is used AS GIVEN.
 *
 * An earlier version reduced the scalar modulo SUB_ORDER as a convenience.
 * That silently broke `isInPrimeSubgroup`: its whole test is
 * `SUB_ORDER * P == identity`, and reducing turned the scalar into zero, so
 * every curve point - including order-2 points - passed. The subgroup check
 * is the thing standing between a bidder and encrypting to a leaky key, so
 * no reduction happens here. Callers that want a reduced scalar reduce it
 * themselves, where the modulus is visible.
 */
export function mulPoint(p: Point, e: bigint): Point {
  if (e < 0n) {
    // Negation is only meaningful within the prime-order subgroup, and no
    // caller needs it, so refuse rather than guess.
    throw new Error("mulPoint: negative scalars are not supported");
  }
  if (e === 0n) return { ...IDENTITY };
  return fromF(jub().mulPointEscalar(toF(p), e));
}

/** g^e for the standard generator. */
export function mulBase(e: bigint): Point {
  return mulPoint(BASE8, e);
}

export function pointsEqual(a: Point, b: Point): boolean {
  return a.x === b.x && a.y === b.y;
}

/** Whether the point satisfies the curve equation. */
export function inCurve(p: Point): boolean {
  if (p.x >= CURVE_PRIME || p.y >= CURVE_PRIME) return false;
  return jub().inCurve(toF(p));
}

/**
 * Whether the point lies in the PRIME-ORDER subgroup.
 *
 * `inCurve` alone is not enough for a point the protocol will encrypt to.
 * BabyJubjub's group order is `8 * SUB_ORDER`, so a point can satisfy the
 * curve equation while carrying a small-order component. Encrypting to such
 * a point leaks information about the plaintext through the small-order part,
 * so the tender public key is checked for subgroup membership before any
 * bidder can encrypt to it.
 */
export function isInPrimeSubgroup(p: Point): boolean {
  if (!inCurve(p)) return false;
  return pointsEqual(mulPoint(p, SUB_ORDER), IDENTITY);
}

/** Negate a point. Twisted Edwards: -(x, y) = (-x, y). */
export function negatePoint(p: Point): Point {
  return { x: p.x === 0n ? 0n : CURVE_PRIME - p.x, y: p.y };
}

/** Modular inverse in the scalar field of the prime-order subgroup. */
export function invModSubOrder(a: bigint): bigint {
  let [old_r, r] = [((a % SUB_ORDER) + SUB_ORDER) % SUB_ORDER, SUB_ORDER];
  let [old_s, s] = [1n, 0n];
  while (r !== 0n) {
    const q = old_r / r;
    [old_r, r] = [r, old_r - q * r];
    [old_s, s] = [s, old_s - q * s];
  }
  if (old_r !== 1n) throw new Error("invModSubOrder: value is not invertible");
  return ((old_s % SUB_ORDER) + SUB_ORDER) % SUB_ORDER;
}
