/**
 * Where the committee's secret shares live in this deployment.
 *
 * This is the honest, ugly part, and it is labelled as such wherever it shows
 * on screen. FairProof's committee key is dealt by a trusted dealer: one party
 * generates the tender secret, splits it five ways, publishes the Feldman
 * commitments the contract verifies, and is then supposed to destroy the
 * secret. In a real deployment each member's share is generated by that member
 * — distributed key generation — and no single machine ever holds all five.
 *
 * Here the dealer is the Authority workspace and the five members are five
 * panels in the same browser. The shares therefore have to be kept somewhere
 * both can reach, which is this: the browser's own storage, on the reader's own
 * machine, never transmitted. It is exactly the residual the whitepaper names
 * in Section 19.1, and pretending otherwise by hiding the storage would be
 * worse than saying it plainly.
 *
 * What is NOT stored: nothing here ever reaches the chain, a server, or a log.
 * The on-chain record holds only the public shares and the commitments.
 */
const KEY = "fairproof.dealings.v1";

export interface StoredDealing {
  tenderId: string;
  tenderIdString: string;
  dealtAt: number;
  /**
   * True when this dealing was served as a file rather than dealt in this
   * browser — see `loadSeededDealings`. The Committee workspace shows a
   * different, blunter caveat for these.
   */
  seeded?: boolean;
  publicKey: { x: string; y: string };
  commitments: { x: string; y: string }[];
  /** One entry per member, 1-based index. The secret material. */
  shares: { index: number; share: string; publicShareX: string; publicShareY: string }[];
  members: string[];
}

type Vault = Record<string, StoredDealing>;

function read(): Vault {
  try {
    const raw = localStorage.getItem(KEY);
    return raw ? (JSON.parse(raw) as Vault) : {};
  } catch {
    // Storage disabled, private mode, or corrupt. An empty vault is the
    // correct answer: the committee simply cannot act, which is visible.
    return {};
  }
}

function write(v: Vault): void {
  try {
    localStorage.setItem(KEY, JSON.stringify(v));
  } catch {
    // Nothing to do but let the caller find no dealing later.
  }
}

export function saveDealing(d: StoredDealing): void {
  const v = read();
  v[d.tenderId] = d;
  write(v);
}

export function loadDealing(tenderId: string): StoredDealing | null {
  return read()[tenderId] ?? null;
}

export function allDealings(): StoredDealing[] {
  return Object.values(read()).sort((a, b) => b.dealtAt - a.dealtAt);
}

export function forgetDealing(tenderId: string): void {
  const v = read();
  delete v[tenderId];
  write(v);
}

/**
 * Dealings served as files, for tenders seeded by `npm run tender`.
 *
 * A tender published from the Authority workspace keeps its shares in the
 * browser that dealt them, which is the honest consequence of a trusted
 * dealer — and it means nobody else can ever open it. A deployment seeded that
 * way dead-ends at the ceremony, so the seed script writes its dealing to
 * `public/committee-dealings/` and this loads it.
 *
 * For a tender seeded that way the five shares sit in one file that anyone can
 * fetch, so its threshold demonstrates the mechanism rather than protecting
 * anything. The Committee workspace says exactly that, on the panel that uses
 * it, rather than letting the three-of-five meter imply otherwise.
 */
export async function loadSeededDealings(): Promise<StoredDealing[]> {
  try {
    const res = await fetch("/committee-dealings/index.json");
    if (!res.ok) return [];
    const { dealings } = (await res.json()) as { dealings?: string[] };
    const out: StoredDealing[] = [];
    for (const name of dealings ?? []) {
      try {
        const r = await fetch(`/committee-dealings/${name}`);
        if (!r.ok) continue;
        const d = (await r.json()) as StoredDealing;
        if (d.tenderId && Array.isArray(d.shares)) out.push({ ...d, seeded: true });
      } catch {
        // One unreadable file does not hide the rest.
      }
    }
    return out;
  } catch {
    // No seeded dealings on this deployment. Not an error.
    return [];
  }
}
