// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

/**
 * @title BabyJubjub
 * @notice Twisted Edwards curve arithmetic, for on-chain Feldman VSS
 *         verification and Chaum-Pedersen DLEQ proofs.
 *
 * @dev Development plan Section 12.2, whitepaper Section 6 (3-of-5 threshold
 *      opening).
 *
 *      BabyJubjub's base field is BN254's SCALAR field, which is what makes
 *      the same arithmetic expressible inside a BN254 circuit, in TypeScript
 *      via circomlibjs, and here. All three must agree exactly; agreement is
 *      enforced by a cross-language test, not assumed.
 *
 * @dev THE ADDITION LAW IS circomlib's, DELIBERATELY.
 *
 *      The affine law for a twisted Edwards curve a*x^2 + y^2 = 1 + d*x^2*y^2
 *      is
 *          x3 = (x1*y2 + y1*x2) / (1 + d*x1*x2*y1*y2)
 *          y3 = (y1*y2 - a*x1*x2) / (1 - d*x1*x2*y1*y2)
 *
 *      which is what `circomlib`'s BabyAdd and circomlibjs implement. Rather
 *      than importing a faster formula from a different coordinate system -
 *      and risking a point encoding that disagrees with the circuit for
 *      reasons that look like a curve bug - this library uses the SAME law,
 *      rewritten projectively so no modular inversion is needed per step:
 *
 *          Z = Z1*Z2,  ZZ = Z*Z,  P = X1*X2,  Q = Y1*Y2,  DD = d*P*Q
 *          numX = (X1*Y2 + Y1*X2) * Z      denX = ZZ + DD
 *          numY = (Q - a*P) * Z            denY = ZZ - DD
 *          X3 = numX*denY,  Y3 = numY*denX,  Z3 = denX*denY
 *
 *      Substituting x = X/Z, y = Y/Z recovers the affine law exactly, so this
 *      is a change of representation and not a change of algorithm.
 *
 *      The law is unified: it computes a doubling correctly with no special
 *      case. A verifier with a separate doubling branch has an untested path
 *      that only fires on equal inputs, which is precisely the input an
 *      attacker can choose.
 *
 * @dev WHY COMPARISON AVOIDS INVERSION. Checking whether a projective result
 *      equals an affine point is `X == x*Z && Y == y*Z`. Converting to affine
 *      instead would cost a modexp per check for no benefit, and the identity
 *      test is simply `X == 0 && Y == Z`.
 */
library BabyJubjub {
    /// @notice The base field prime, equal to BN254's scalar field prime.
    uint256 internal constant P =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Curve parameters: A*x^2 + y^2 = 1 + D*x^2*y^2.
    uint256 internal constant A = 168700;
    uint256 internal constant D = 168696;

    /**
     * @notice Order of the prime-order subgroup generated by BASE8.
     * @dev The full curve group has order 8 * SUB_ORDER. Every secret scalar
     *      and every Lagrange coefficient lives modulo SUB_ORDER, never
     *      modulo P and never modulo the full order.
     */
    uint256 internal constant SUB_ORDER =
        2736030358979909402780800718157159386076813972158567259200215660948447373041;

    /// @notice Generator of the prime-order subgroup (circomlib's Base8).
    uint256 internal constant BASE8X =
        5299619240641551281634865583518297030282874472190772894086521144482721001553;
    uint256 internal constant BASE8Y =
        16950150798460657717958625567821834550301663161624707787222815936182638968203;

    /// @notice A projective point (X : Y : Z), with x = X/Z and y = Y/Z.
    struct Proj {
        uint256 x;
        uint256 y;
        uint256 z;
    }

    error NotOnCurve(uint256 x, uint256 y);
    error CoordinateOutOfField(uint256 value);

    /// @notice The identity element, (0 : 1 : 1).
    function identity() internal pure returns (Proj memory) {
        return Proj(0, 1, 1);
    }

    /// @notice Lift an affine point into projective coordinates.
    function toProj(uint256 x, uint256 y) internal pure returns (Proj memory) {
        return Proj(x, y, 1);
    }

    /**
     * @notice Whether (x, y) satisfies the curve equation.
     * @dev Coordinates at or above P are rejected rather than reduced: an
     *      unreduced coordinate that happens to satisfy the equation after
     *      reduction is a different encoding of the same point, and accepting
     *      two encodings of one point breaks any check that compares points
     *      for equality.
     */
    function inCurve(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= P || y >= P) return false;
        uint256 xx = mulmod(x, x, P);
        uint256 yy = mulmod(y, y, P);
        uint256 lhs = addmod(mulmod(A, xx, P), yy, P);
        uint256 rhs = addmod(1, mulmod(D, mulmod(xx, yy, P), P), P);
        return lhs == rhs;
    }

    /// @notice Revert unless (x, y) is a valid curve point.
    function requireOnCurve(uint256 x, uint256 y) internal pure {
        if (x >= P) revert CoordinateOutOfField(x);
        if (y >= P) revert CoordinateOutOfField(y);
        if (!inCurve(x, y)) revert NotOnCurve(x, y);
    }

    /**
     * @notice Unified projective addition. Handles doubling with no branch.
     */
    function add(Proj memory p1, Proj memory p2) internal pure returns (Proj memory) {
        uint256 z = mulmod(p1.z, p2.z, P);
        uint256 zz = mulmod(z, z, P);
        uint256 xx = mulmod(p1.x, p2.x, P);
        uint256 yy = mulmod(p1.y, p2.y, P);
        uint256 dd = mulmod(D, mulmod(xx, yy, P), P);

        uint256 cross = addmod(mulmod(p1.x, p2.y, P), mulmod(p1.y, p2.x, P), P);
        uint256 numX = mulmod(cross, z, P);
        uint256 denX = addmod(zz, dd, P);

        // yy - A*xx and zz - dd, in the field.
        uint256 numY = mulmod(addmod(yy, P - mulmod(A, xx, P) % P, P), z, P);
        uint256 denY = addmod(zz, P - dd % P, P);

        return
            Proj(
                mulmod(numX, denY, P),
                mulmod(numY, denX, P),
                mulmod(denX, denY, P)
            );
    }

    /**
     * @notice Scalar multiplication by double-and-add, most significant bit
     *         first.
     *
     * @dev NOT constant time, and it does not need to be: every scalar this
     *      library multiplies by is public - a member index, a small power of
     *      one, a Lagrange coefficient, or SUB_ORDER itself. No secret scalar
     *      is ever multiplied on-chain, because a secret on-chain is not a
     *      secret.
     */
    function mul(Proj memory p, uint256 scalar) internal pure returns (Proj memory) {
        Proj memory acc = identity();
        if (scalar == 0) return acc;
        // Skip leading zero bits so a small scalar costs a small number of
        // doublings; the Feldman check multiplies by values below 32.
        uint256 bit = 1 << 255;
        while (bit != 0 && (scalar & bit) == 0) bit >>= 1;
        while (bit != 0) {
            acc = add(acc, acc);
            if (scalar & bit != 0) acc = add(acc, p);
            bit >>= 1;
        }
        return acc;
    }

    /// @notice Whether a projective point is the identity.
    function isIdentity(Proj memory p) internal pure returns (bool) {
        return p.x == 0 && p.y == p.z && p.z != 0;
    }

    /// @notice Whether a projective point equals an affine one, inversion-free.
    function equalsAffine(Proj memory p, uint256 x, uint256 y)
        internal
        pure
        returns (bool)
    {
        return
            mulmod(x, p.z, P) == p.x % P &&
            mulmod(y, p.z, P) == p.y % P;
    }

    /**
     * @notice Whether (x, y) lies in the PRIME-ORDER subgroup.
     *
     * @dev `inCurve` is not sufficient for a point the protocol will encrypt
     *      to. The group order is 8 * SUB_ORDER, so a point can satisfy the
     *      curve equation while carrying a small-order component, and
     *      encrypting to such a point leaks information about the plaintext
     *      through that component. The tender public key therefore gets this
     *      check before any bidder can encrypt to it.
     */
    function isInPrimeSubgroup(uint256 x, uint256 y) internal pure returns (bool) {
        if (!inCurve(x, y)) return false;
        return isIdentity(mul(toProj(x, y), SUB_ORDER));
    }

    /**
     * @notice The public share a correct Feldman dealer must have produced:
     *
     *             Y_i = sum_j (i^j) * C_j
     *
     * @dev This is the entire content of Feldman's verifiability, and
     *      computing it here is what turns "a dishonest dealer is detectable"
     *      into "a dishonest dealer is rejected". `index` is 1-based: index 0
     *      would evaluate the polynomial at zero, which IS the secret, so no
     *      member may ever hold it.
     *
     *      The powers i^j are reduced modulo SUB_ORDER, the order of the group
     *      the exponents live in. Reducing modulo P instead would produce
     *      shares that verify individually and then fail to reconstruct.
     */
    function expectedPublicShare(
        uint256[] memory commitmentX,
        uint256[] memory commitmentY,
        uint256 index
    ) internal pure returns (Proj memory) {
        Proj memory acc = identity();
        uint256 power = 1;
        for (uint256 j = 0; j < commitmentX.length; j++) {
            acc = add(acc, mul(toProj(commitmentX[j], commitmentY[j]), power));
            power = mulmod(power, index, SUB_ORDER);
        }
        return acc;
    }
}
